spring:
  datasource:
    url: jdbc:postgresql://fsa-db-1.czsvju11gz4n.eu-north-1.rds.amazonaws.com/fsa
    username: fsa
    password: 'Fsa!!Dev123!#'
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
