server:
  servlet:
    context-path: /api/

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://fsa-1.clbvsufdwhgu.us-east-1.rds.amazonaws.com/fsa
    username: fsa
    password: 'Fsa!!Dev123!#'
    driver-class-name: org.postgresql.Driver
fsa:
  security:
    rsa:
      private-key: classpath:certs/private.pem
      public-key: classpath:certs/public.pem

