server:
  servlet:
    context-path: /api/

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
fsa:
  security:
    rsa:
      private-key: classpath:certs/private.pem
      public-key: classpath:certs/public.pem

