version: '3.1'

services:

  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: fsa
      POSTGRES_PASSWORD: fsa
      POSTGRES_DB: fsa
    ports:
      - 5432:5432